name: Test Deployment

on:
  pull_request:
    branches:
      - pre-release

jobs:
  test-deploy:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: npm install
      - name: Test Website Build
        run: npm run build
